## Lab Demo COMP7035 Topic 5
### Objective 
- Numpy arrays
- Numpy Indexing and Selection
- Numpy Operation

## What is NumPy ?

- **NumPy** (standing for Numerical Python) is a popular library in Python that can efficiently process **multidimensional data arrays**. It is also the foundation of other advanced Python libraries such as **Pandas**.

**Examples of 1‐dimensinoal array**: the elements must have the same data type

In [1]:
[2,7,10,6] # an array of integers, shape is (4)
[73.5, 67.0, 75.5, 58.5, 92.0] # an array of stduent grades or stock prices, shape is (5)
['Sam', 'John', 'Zoe'] # an array of names, shape is (3)

['Sam', 'John', 'Zoe']

**Example of 2‐diminsionial array**: an array of array with the same shape and data type

In [2]:
[[3,6,4,8],
[2,7,5,9],
[4,8,6,1]] 



# an array with 3 elements, each element is an array with 4 integers, shape is (3,4)

[[3, 6, 4, 8], [2, 7, 5, 9], [4, 8, 6, 1]]

## List vs. Array

- Arrays need extra declaration while lists don’t.
- Lists are generally used more often between the two, which works fine most of the time. 
- If you're going to perform arithmetic functions to your lists, you should really be using arrays instead. 
- Arrays will store your data more compactly and efficiently. 

## The major features of NumPy
- Easily generate and store data in memory in the form of multidimensional array
- Easily load and store data on disk in **binary**, **text**, or **CSV format**
- Support **efficient** operations on data arrays, including basic arithmetic and logical operations, shape manipulation, data sorting, data slicing, linear algebra, statistical operation, discrete Fourier transform, etc.
- Vectorised computation: simple syntax for elementwise operations without using loops (e.g., **a** = **b** + **c** where **a**, **b**, and **c** are three multidimensional arrays with same shape).

## Numpy Basics

### Create an array of the integers from 20 to 50.

In [56]:
import numpy as np
# arange(start, stop): Values are generated within the half-open interval [start, stop)
# The interval including start but excluding stop
array=np.arange(20,51)
print("Array of the integers from 20 to 50")
print(array)


# arange(start, stop): Values are generated within the half-open interval [start, stop).
# The interval including start but excluding stop



Array of the integers from 20 to 50
[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43
 44 45 46 47 48 49 50]


### Create an array of the integers from 0 to 50 with evenly spacing of 10.

In [57]:
import numpy as np
array = np.linspace(0,51,6)
print(array)
array = np.linspace(0,50,6)
print(array)




[ 0.  10.2 20.4 30.6 40.8 51. ]
[ 0. 10. 20. 30. 40. 50.]


### Show different prpoerties of the numpy array

In [58]:
array = np.arange(20) 
print(array) 
array = array.reshape(4,5)
print(array)
print(type(array))
print(array.ndim)
print(array.shape)
print(array.dtype) 
print(array.itemsize) 
print(array.size)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
<class 'numpy.ndarray'>
2
(4, 5)
int32
4
20


### Create an array of the integers from 9 to 31 and print all values except the first and the last.

In [22]:
array = np.arange(9,32) 
print(array[1:-1])

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30]


### Create an array of 5 zeros, 5 ones, 5 fives

In [27]:
array = np.zeros(5)
print("An array of 5 zeros:")
print(array)
array = np.ones(5)
print("An array of 5 ones:")
print(array)
array = np.ones(5)*5
print("An array of 5 fives:")
print(array)

An array of 5 zeros:
[0. 0. 0. 0. 0.]
An array of 5 ones:
[1. 1. 1. 1. 1.]
An array of 5 fives:
[5. 5. 5. 5. 5.]


### Create a 5x5 zero matrix with elements with the diagonal equal to 5, 4, 3, 2, 1

In [28]:
array = np.diag([5, 4, 3, 2, 1])
print(array)

[[5 0 0 0 0]
 [0 4 0 0 0]
 [0 0 3 0 0]
 [0 0 0 2 0]
 [0 0 0 0 1]]


### Find missing item in a given array

In [32]:

array = np.array([[1, 2, np.nan, 3],
 [np.nan, 5, 6, 7],
 [8, np.nan, 10, 11]])
print(np.isnan(array))

[[False False  True False]
 [ True False False False]
 [False  True False False]]


### Indexing row and column

In [37]:
array = np.array(([5,10,15],[20,25,30],[35,40,45]))
print(array[1])

[20 25 30]


In [38]:
# acceess in individual item
print(array[1][0])

20


In [55]:
# Array slicing  
print(array[:])
print(array[0:2,1:3])

[[ 5 10 15]
 [20 25 30]
 [35 40 45]]
[[10 15]
 [25 30]]


## More indexing example
<img src= 'https://media.geeksforgeeks.org/wp-content/uploads/Numpy1.jpg' width=500/>  
Image source: https://www.geeksforgeeks.org/numpy-indexing/